### ISSUE TITLE
[Android-YYC] Black textures compiling on Android with YYC

### ISSUE THREAD

**Issue by SantiFerre** [YoYoGames/GM-GPUTextureCompression#1]
### Description

When I compile on Android with `YYC`, on some android devices, textures are not visible when compressed with the `ASTC` mode extension. The textures look black.

#### Works well:

- Xiaomi MI8 Explorer Edition: 
    - Android 10 QKQ1.190828.002
    - Architecture: ARM64
- Xiaomi Poco X3 Pro:
    - Android 12 SKQ1.211006.001
    - Architecture: ARM64

#### Not working:

- Moto G42:
    - Android 13
    - Architecture: ARM64 
- Emulator (Nexus 5 API 34):
    - Android 14
    - Architecture: x86_64

### Gamemaker Version:
IDE v2024.4.1.152
Runtime v2024.4.1.202

### Steps To Reproduce

1. Start GameMaker and clone this github project
2. Open AVD Emulator and create an Android 14 emulator
3. Run project with YYC
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Monthly

### Which platform(s) are you seeing the problem on?

Android

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by okashusmani** [comment]
My app got suspended from Googleplay because of this issue. They kept rejecting the app submission because of black screen as ASTC compressed textures are not being supported on many devices. On Amazon app store they are rejecting the app each time because of same issue and gave me a log file too. Please solve this issue as soon as possible. It needs attention urgently.
[Problem.txt](https://github.com/user-attachments/files/16945507/Problem.txt)

**Comment by brankoblazevic** [comment]
I also encountered several devices where the textures appear black, meaning players only see a black screen. These are devices that, according to their specs, support ASTC compression, but it still doesn't work.

The devices that don't work are:

    Samsung Galaxy A01 Core
    Samsung Galaxy A04e

After player complaints, I had to urgently remove this GPU compression.

It's a shame it doesn't work reliably on all devices.

**Comment by JonnoRobson** [comment]
Thank you to you both for flagging this problem with our ASTC support on Android. Checking those Samsung devices [here](https://opengles.gpuinfo.org/) , it looks like the problem comes from certain devices supporting the GL extension `GL_KHR_texture_compression_astc_ldr` but not supporting `GL_OES_texture_compression_astc`. Currently GameMaker checks for the latter extension on app startup to see if the device will be able to support ASTC compressed textures. That extension actually provides extra features that GameMaker is not utilising so supporting only the `GL_KHR_texture_compression_astc_ldr` extension should be enough for a device to load ASTC textures.

I've created an issue in the main bug tracking repo in order to track any changes that get made to resolve this issue https://github.com/YoYoGames/GameMaker-Bugs/issues/7931

**Comment by JonnoRobson** [comment]
I'm going to close this issue for now as a fix has gone into the GameMaker runtime that should resolve the issue and no further action is needed in the texture compression extension itself. Again, anyone wanting to keep track of the progress of this issue should follow https://github.com/YoYoGames/GameMaker-Bugs/issues/7931
